### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by jacarval** [BarakChamo/mobileShooter#1]
Serious
- [x] player metrics
- [ ] cannon recoil on fire
- [ ] Onboarding on console and controller
- [ ] Take photo or choose Emoji on phone
- [ ] Send stats to phone
- [ ] Handle animations on collision
- [ ] leaderboard
- [x] collision with pick-ups (kevins)
- [ ] implement raft
- [x] targeting socket -- sending player messages on controller
- [ ] composed player shapes 
- [x] graphics, background, etc
- [x] sound effects
- [x] worker+++ (maybe)
- [x] collision detection
- [x] room management (multiple games)
- [x] vibration events
- [x] sounds coming through phone
- [ ] profile photos
- [ ] wrap in raspberry pi
- [ ] record vocals
- [x] power-ups
- [ ] mobile interface/UI
- [x] prevent render overflow

Not so serious
